//Aluno: Rafael Cruz - RA: 2266261
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadJetTab extends javax.swing.JFrame {

    JetSki jetski = new JetSki();
    GerEmb ger = new GerEmb();
    /**
     * Creates new form CadEmb
     */
    public CadJetTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        rotJetSki = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rotJetSki.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        rotJetSki.setForeground(new java.awt.Color(0, 0, 255));
        rotJetSki.setText("JetSki");

        tblJet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Potencia", "Eficiencia", "Autonomia"
            }
        ));
        jScrollPane1.setViewportView(tblJet);
        if (tblJet.getColumnModel().getColumnCount() > 0) {
            tblJet.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblJet.getColumnModel().getColumn(2).setPreferredWidth(55);
            tblJet.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblJet.getColumnModel().getColumn(4).setPreferredWidth(35);
            tblJet.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rotJetSki)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotJetSki)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void ListJet2(GerEmb ger){
        jetski = new JetSki();
        
        DefaultTableModel modelo = (DefaultTableModel) tblJet.getModel();
        modelo.setRowCount(0);
        
        for(int posLin = 0; posLin < ger.getBdJet().size(); posLin++){
            
            try{
                jetski.setCodigo(ger.getBdJet().get(posLin).getCodigo());
                jetski.setNome(ger.getBdJet().get(posLin).getNome());
                jetski.setTipo(ger.getBdJet().get(posLin).getTipo());
                jetski.setCapacidade(ger.getBdJet().get(posLin).getCapacidade());
                jetski.setPotencia(ger.getBdJet().get(posLin).getPotencia());
                jetski.setEficiencia(ger.getBdJet().get(posLin).getEficiencia());  
                
                modelo.insertRow(posLin, new Object[]{jetski.getCodigo(), jetski.nomeEmbarc(), 
                jetski.getTipo(), jetski.getPotencia(), jetski.getEficiencia(),
                jetski.autonomia()});
            }
            catch(NumNegatException nne){
                 nne.impNNE();                
             }
            catch(BlankStringException bse){
                bse.impBlank();
            }
            catch(SupCapacidade SPC){
                SPC.impSCP();
            }
        }
    }

   public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0)
            dispose();
   }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadJetTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotJetSki;
    private javax.swing.JTable tblJet;
    // End of variables declaration//GEN-END:variables
}
