//Aluno: Rafael Cruz - RA: 2266261

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadVelTab extends javax.swing.JFrame {

    Veleiro veleiro = new Veleiro();
    /**
     * Creates new form CadEmb
     */
    public CadVelTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        rotVeleiro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rotVeleiro.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rotVeleiro.setForeground(new java.awt.Color(255, 51, 51));
        rotVeleiro.setText("Veleiro");

        tblVel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Tripulacao", "Comprimento", "Mastros", "Velas", "Ingressos", "Autonomia"
            }
        ));
        jScrollPane1.setViewportView(tblVel);
        if (tblVel.getColumnModel().getColumnCount() > 0) {
            tblVel.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(2).setPreferredWidth(55);
            tblVel.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(4).setPreferredWidth(25);
            tblVel.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(6).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(7).setPreferredWidth(35);
            tblVel.getColumnModel().getColumn(8).setPreferredWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rotVeleiro)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rotVeleiro)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed
    
    public void ListVel2(GerEmb ger){
        veleiro = new Veleiro();
        
        DefaultTableModel modelo = (DefaultTableModel) tblVel.getModel();
        modelo.setRowCount(0);
        
        for(int posLin = 0; posLin < ger.getBdVel().size(); posLin++){
            
            try{
                veleiro.setCodigo(ger.getBdVel().get(posLin).getCodigo());
                veleiro.setNome(ger.getBdVel().get(posLin).getNome());
                veleiro.setTipo(ger.getBdVel().get(posLin).getTipo());
                veleiro.setTripulacao(ger.getBdVel().get(posLin).getTripulacao());
                veleiro.setComprimento(ger.getBdVel().get(posLin).getComprimento());
                veleiro.setMastros(ger.getBdVel().get(posLin).getMastros());
                veleiro.setVelas(ger.getBdVel().get(posLin).getVelas());  
                veleiro.setCapacidade(ger.getBdVel().get(posLin).getCapacidade());
                
                modelo.insertRow(posLin, new Object[]{veleiro.getCodigo(), veleiro.nomeEmbarc(), 
                veleiro.getTipo(), veleiro.getTripulacao(), veleiro.getComprimento(), veleiro.getMastros(),
                veleiro.getVelas(),  veleiro.ingresso(),  veleiro.autonomia()});
            }
            catch(NumNegatException nne){
                 nne.impNNE();                
             }
            catch(BlankStringException bse){
                bse.impBlank();
            }
            catch(SupCapacidade SPC){
                SPC.impSCP();
            }
        }
    }
    
   public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0)
            dispose();
   }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadVelTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotVeleiro;
    private javax.swing.JTable tblVel;
    // End of variables declaration//GEN-END:variables
}
