//Aluno: Rafael Cruz - RA: 2266261
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CadVel extends javax.swing.JFrame {

    Veleiro veleiro = new Veleiro();
    GerEmb ger = new GerEmb();
    /**
     * Creates new form CadEmb
     */
    public CadVel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        rotVeleiro = new javax.swing.JLabel();
        cxVelTipo = new javax.swing.JTextField();
        cxVelTrip = new javax.swing.JTextField();
        cxVelComp = new javax.swing.JTextField();
        cxVelMastros = new javax.swing.JTextField();
        btVelCad = new javax.swing.JButton();
        btVelLimp = new javax.swing.JButton();
        rotVelCod = new javax.swing.JLabel();
        rotVelNome = new javax.swing.JLabel();
        rotVelTipo = new javax.swing.JLabel();
        rotVelTrip = new javax.swing.JLabel();
        rotVelComp = new javax.swing.JLabel();
        rotVelMastrol = new javax.swing.JLabel();
        cxVelCod = new javax.swing.JTextField();
        cxVelNome = new javax.swing.JTextField();
        rotVelVelas = new javax.swing.JLabel();
        rotVelSup = new javax.swing.JLabel();
        cxVelVelas = new javax.swing.JTextField();
        cxVelSup = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVel = new javax.swing.JTable();
        ChamaCadNavTab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rotVeleiro.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rotVeleiro.setForeground(new java.awt.Color(255, 51, 51));
        rotVeleiro.setText("Veleiro");

        btVelCad.setText("Cadastrar");
        btVelCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVelCadActionPerformed(evt);
            }
        });

        btVelLimp.setText("Limpar");
        btVelLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVelLimpActionPerformed(evt);
            }
        });

        rotVelCod.setText("Codigo:");

        rotVelNome.setText("Nome:");

        rotVelTipo.setText("Tipo:");

        rotVelTrip.setText("Tripulacao:");

        rotVelComp.setText("Comprimento do Navio:");

        rotVelMastrol.setText("Mastros");

        rotVelVelas.setText("Velas:");

        rotVelSup.setText("Suprimentos:");

        tblVel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Tipo", "Tripulacao", "Comprimento", "Mastros", "Velas", "Ingressos", "Autonomia"
            }
        ));
        jScrollPane1.setViewportView(tblVel);
        if (tblVel.getColumnModel().getColumnCount() > 0) {
            tblVel.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(2).setPreferredWidth(55);
            tblVel.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(4).setPreferredWidth(25);
            tblVel.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(6).setPreferredWidth(20);
            tblVel.getColumnModel().getColumn(7).setPreferredWidth(35);
            tblVel.getColumnModel().getColumn(8).setPreferredWidth(30);
        }

        ChamaCadNavTab.setText("Chama 3º Formulario");
        ChamaCadNavTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaCadNavTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ChamaCadNavTab)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotVelSup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxVelSup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btVelCad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btVelLimp))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rotVelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rotVelCod))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxVelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxVelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotVelMastrol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxVelMastros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotVelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxVelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotVelVelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxVelVelas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rotVelTrip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cxVelTrip))
                                    .addComponent(rotVelComp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxVelComp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rotVeleiro)))
                        .addGap(179, 179, 179))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rotVeleiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelCod)
                    .addComponent(cxVelCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelNome)
                    .addComponent(cxVelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelTipo)
                    .addComponent(cxVelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelTrip)
                    .addComponent(cxVelTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelComp)
                    .addComponent(cxVelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelMastrol)
                    .addComponent(cxVelMastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelVelas)
                    .addComponent(cxVelVelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotVelSup)
                    .addComponent(cxVelSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVelCad)
                    .addComponent(btVelLimp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChamaCadNavTab)
                    .addComponent(btSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btVelCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVelCadActionPerformed
        cadVel();
        ListVel();
    }//GEN-LAST:event_btVelCadActionPerformed

    private void btVelLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVelLimpActionPerformed
        LimparVel();
    }//GEN-LAST:event_btVelLimpActionPerformed

    private void ChamaCadNavTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaCadNavTabActionPerformed
        CadVelTab cadVelTab = new CadVelTab();
        cadVelTab.ListVel2(ger);
        cadVelTab.setVisible(true);
    }//GEN-LAST:event_ChamaCadNavTabActionPerformed
    
    public void ListVel(){
        veleiro = new Veleiro();
        
        DefaultTableModel modelo = (DefaultTableModel) tblVel.getModel();
        modelo.setRowCount(0);
        
        for(int posLin = 0; posLin < ger.getBdVel().size(); posLin++){
            
            try{
                veleiro.setCodigo(ger.getBdVel().get(posLin).getCodigo());
                veleiro.setNome(ger.getBdVel().get(posLin).getNome());
                veleiro.setTipo(ger.getBdVel().get(posLin).getTipo());
                veleiro.setTripulacao(ger.getBdVel().get(posLin).getTripulacao());
                veleiro.setComprimento(ger.getBdVel().get(posLin).getComprimento());
                veleiro.setMastros(ger.getBdVel().get(posLin).getMastros());
                veleiro.setVelas(ger.getBdVel().get(posLin).getVelas());  
                veleiro.setCapacidade(ger.getBdVel().get(posLin).getCapacidade());
                
                modelo.insertRow(posLin, new Object[]{veleiro.getCodigo(), veleiro.nomeEmbarc(), 
                veleiro.getTipo(), veleiro.getTripulacao(), veleiro.getComprimento(), veleiro.getMastros(),
                veleiro.getVelas(),  veleiro.ingresso(),  veleiro.autonomia()});
            }
            catch(NumNegatException nne){
                 nne.impNNE();                
             }
            catch(BlankStringException bse){
                bse.impBlank();
            }
            catch(SupCapacidade SPC){
                SPC.impSCP();
            }
        }
    }
   
   public void LimparVel(){
        cxVelCod.setText("");
        cxVelNome.setText("");
        cxVelTipo.setText("");
        cxVelTrip.setText("");
        cxVelComp.setText("");
        cxVelMastros.setText("");
        cxVelVelas.setText("");
        cxVelSup.setText("");
        cxVelCod.requestFocus();
   }
   
   public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Realmente sair?", "Saida", JOptionPane.YES_NO_OPTION);
        if(resp == 0)
            dispose();
   }
   
   public void cadVel(){
       
        try{
            veleiro.setCodigo(Integer.parseInt(cxVelCod.getText()));         
            veleiro.setTripulacao(Integer.parseInt(cxVelTrip.getText()));
            veleiro.setComprimento(Double.parseDouble(cxVelComp.getText()));
            veleiro.setMastros(Integer.parseInt(cxVelMastros.getText()));
            veleiro.setVelas(Integer.parseInt(cxVelVelas.getText()));
            veleiro.setCapacidade(Double.parseDouble(cxVelSup.getText()));
            veleiro.setNome(cxVelNome.getText());
            veleiro.setTipo(cxVelTipo.getText());

            veleiro = ger.cadVeleiro(veleiro);

            if(veleiro != null){
                JOptionPane.showMessageDialog(null, "Cadastro confirmado", "Cadastro", JOptionPane.PLAIN_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null, "Ja existe alguem com este Veleiro, Cadastro nao executado", "Erro", JOptionPane.ERROR_MESSAGE);    
        }
        catch(NumNegatException nne){
            nne.impNNE();
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Escreva um numero:", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        catch(SupCapacidade SPC){
            SPC.impSCP();
        }
        catch(BlankStringException bse){
            bse.impBlank();
        }    
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadNav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadVel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChamaCadNavTab;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVelCad;
    private javax.swing.JButton btVelLimp;
    private javax.swing.JTextField cxVelCod;
    private javax.swing.JTextField cxVelComp;
    private javax.swing.JTextField cxVelMastros;
    private javax.swing.JTextField cxVelNome;
    private javax.swing.JTextField cxVelSup;
    private javax.swing.JTextField cxVelTipo;
    private javax.swing.JTextField cxVelTrip;
    private javax.swing.JTextField cxVelVelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotVelCod;
    private javax.swing.JLabel rotVelComp;
    private javax.swing.JLabel rotVelMastrol;
    private javax.swing.JLabel rotVelNome;
    private javax.swing.JLabel rotVelSup;
    private javax.swing.JLabel rotVelTipo;
    private javax.swing.JLabel rotVelTrip;
    private javax.swing.JLabel rotVelVelas;
    private javax.swing.JLabel rotVeleiro;
    private javax.swing.JTable tblVel;
    // End of variables declaration//GEN-END:variables
}
